### ISSUE TITLE
TypeError: log() got an unexpected keyword argument 'ascii_encode'

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-healthcheck#1]
Dear Dev. As I really appreciate your efforts in this app and I reallyw would like to use it I would like to ask you kindly to help me with this error:

```
2019-09-23 21:41:42.807302 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/appdaemon/apps/notifreeze/notifreeze.py", line 58, in initialize
    self.log, APP_NAME, self.app_config, self.sensors
  File "/usr/lib/python3.7/site-packages/adutils/__init__.py", line 26, in show_info
    log(app_name, ascii_encode=bool(icon))
TypeError: log() got an unexpected keyword argument 'ascii_encode'

2019-09-23 21:41:42.807411 WARNING AppDaemon: ------------------------------------------------------------
2019-09-23 21:41:57.908466 INFO AppDaemon: Reading config
2019-09-23 21:41:58.032635 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2019-09-23 21:41:58.032946 INFO AppDaemon: App 'notifreeze' deleted
2019-09-23 21:42:00.042750 INFO AppDaemon: Reading config
2019-09-23 21:42:00.213808 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2019-09-23 21:42:16.458023 INFO AppDaemon: Removing module /config/appdaemon/apps/notifreeze/notifreeze.py
2019-09-23 21:43:55.435645 INFO AppDaemon: Adding /config/appdaemon/apps/batterycheck to module import path
2019-09-23 21:43:55.438048 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/batterycheck/batterycheck.py - ignoring
2019-09-23 21:44:08.722503 INFO AppDaemon: Reloading Module: /config/appdaemon/apps/batterycheck/batterycheck.py
2019-09-23 21:44:08.722846 WARNING AppDaemon: No app description found for: batterycheck - ignorin
```
I am using the Hassio Appdaemoon Which throws this error. I know you already adressed this 2018 
https://github.com/home-assistant/appdaemon/commit/aaf8dc356cb42e83930ff86ad1f774fab7fa7d5e

But apparantly it is gone agan. So it makes you app useless for Hassio Users.

**Comment by benleb** [comment]
sorry, the healthcheck needs the version 4 (currently beta) of appdaemon or the current master/dev branch. I made this clear in the readme now, my fault... sorry!
